services:
  - type: web
    name: client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js # Change to `npm start` if that's in your package.json
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
