services:
  - type: web
    name: ai-resume-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    plan: free

  - type: web
    name: ai-resume-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
